[추가] 폴리라인 생성 옵션에 map을 추가
JaeSeoKim/kakao.maps.d.ts pull request #11
Opened 2023-09-09 08:06 UTC by heozeop

안녕하세요! 폴리라인 생성 옵션에 map이 없어 추가했습니다!
참고한 코드는 [다음](https://apis.map.kakao.com/web/sample/calculatePolylineDistance/)입니다.

> 카카오 웹뷰 선의 거리 계산하기에서 발췌
```typescript
        // 클릭한 위치를 기준으로 선을 생성하고 지도위에 표시합니다
        clickLine = new kakao.maps.Polyline({
            map: map, // 선을 표시할 지도입니다 
            path: [clickPosition], // 선을 구성하는 좌표 배열입니다 클릭한 위치를 넣어줍니다
            strokeWeight: 3, // 선의 두께입니다 
            strokeColor: '#db4040', // 선의 색깔입니다
            strokeOpacity: 1, // 선의 불투명도입니다 0에서 1 사이값이며 0에 가까울수록 투명합니다
            strokeStyle: 'solid' // 선의 스타일입니다
        });
        
```

2023-09-09 13:35 UTC, JaeSeoKim commented on @types/Polyline.d.ts
> +    map?: Map | Roadview | Roadview;
테스트를 해보니 `Map`를 받고 있는 것을 확인했습니다.! 문서상에도 `Map`를 받는 형태로 예시가 작성되어 있지만, Options에 포함이 안되어 있어서 타입 정의를 못한 것 같습니다.
추가로 `Polyline` 이외에 `Circle`, `Rectangle`, `Polygon` 등 다양한 도형 타입에도 추가가 가능한 것으로 확인되었습니다.!

다만, `Roadview`의 경우 실제로 테스트 해본 결과 동작하지 않고, 문서 상에도 존재하지 않아 해당 부분은 수정되어야 할 것 같습니다. (+ 추가로 `Roadview | Roadview` 중복으로 작성하신 부분 때문에 만약 해당 옵션을 받더라도 수정이 이루어져야 할 것 같습니다 ㅠㅠ)

기여 감사합니다.!

```suggestion
    /**
     * 폴리라인이 올라갈 지도
     */
    map?: Map;
```

2023-09-09 13:35 UTC, JaeSeoKim requested changes
기여 감사합니다.! 리뷰에 남긴 사항만 해결되면 바로 Merge 가능할 것 같습니다.!

2023-09-10 05:44 UTC, heozeop commented on @types/Polyline.d.ts
> +    map?: Map | Roadview | Roadview;
엇! 제가 로드뷰의 정의를 헷갈려서 두번 작업하게 만들었네요. 죄송합니다!
circle과 rectangle, polygon에서도 추가 가능하다면 함께 추가해 올리겠습니다!
빠른 리뷰 감사합니다!

2023-09-10 13:21 UTC, JaeSeoKim approved these changes
LGTM 👍

2023-09-10 13:21 UTC, merged

2023-09-10 13:30 UTC, JaeSeoKim commented
@heozeop  [v0.1.39](https://www.npmjs.com/package/kakao.maps.d.ts/v/0.1.39)으로  npm에 배포하엿습니다.! 기여 감사합니다~!!!!