chore: rename Circel.d.ts to Circle.d.ts
JaeSeoKim/kakao.maps.d.ts pull request #12
Opened 2024-05-27 01:43 UTC by LireEruel

클래스 이름이 Circle 이므로 파일 이름도 Circel이 아닌, Circle가 되어야 한다 생각하여 수정하였습니다.

또한 Ellipse.d.ts의 setEllipseOptions에는 세미콜론이 있기 때문에 통일하였습니다.

```typescript
// Ellipse.d.ts
type setEllipseOptions = Partial<EllipseOptions>;
```

2024-05-31 09:35 UTC, JaeSeoKim approved these changes
LGTM:)

2024-06-01 08:17 UTC, JaeSeoKim requested changes
최근 회사에 다니게 되어서 리뷰를 제대로 진행하지 못하였네요.!

https://github.com/JaeSeoKim/kakao.maps.d.ts/blob/09302b118ce2c4a0722d4a761cd9f062639c0f60/%40types/index.d.ts#L35

위 라인도 같이 수정되면 좋을 것 같습니다!

2024-06-10 09:19 UTC, LireEruel commented
> 최근 회사에 다니게 되어서 리뷰를 제대로 진행하지 못하였네요.!
> 
> https://github.com/JaeSeoKim/kakao.maps.d.ts/blob/09302b118ce2c4a0722d4a761cd9f062639c0f60/%40types/index.d.ts#L35
> 
> 위 라인도 같이 수정되면 좋을 것 같습니다!

안녕하세요. 리뷰를 너무 늦게 보았네요.
수정하였습니다!

2024-06-16 10:44 UTC, JaeSeoKim approved these changes

2024-06-16 10:44 UTC, merged

2024-06-16 10:52 UTC, JaeSeoKim commented
[v0.1.40](https://www.npmjs.com/package/kakao.maps.d.ts/v/0.1.40) 버전으로 배포완료 하였습니다.

2024-06-18 08:04 UTC, LireEruel commented
감사합니다! XD